### ISSUE TITLE
Opens blank chrome window

### ISSUE THREAD

**Issue by BlueDrink9** [terhorst/rstviewer#3]
On my arch, installed via `pip`, this opens a blank chrome window rather than previewing the rst. It might be worth printing out the port and address to the console as a backup.

Adding `-v` doesn't output anything extra.

**Comment by terhorst** [comment]
Try `-vv` to enable debug output.

**Comment by BlueDrink9** [comment]
Thanks for the suggesting. I ended up uninstalling and using restview, which had a similar problem but printed the port so I could still use it.

It would be useful for the `-vv` option to appear in the usage text.
