### ISSUE TITLE
"ValueError: list.remove(x): x not in list" breaks socket, browser gets 404

### ISSUE THREAD

**Issue by jamescooke** [terhorst/rstviewer#4]
Hi - thanks for this nice tool 👍🏻 

I've come across the following bug - I guess there's a problem with the rendering done by docutils?

```sh
$ rstviewer 210212_review.rst
```

```
ValueError: list.remove(x): x not in list
Exiting due to error.  Use "--traceback" to diagnose.
Please report errors to <docutils-users@lists.sf.net>.
Include "--traceback" output, Docutils version (0.16 [release]),
Python version (3.8.5), your OS type & version, and the
command line used.
```

When the browser window appears it gets "404: Not Found".

The contents of the file have a subtitle with not enough underline:

```rst
Title
=====

Longer sub title
---
```

This might be a bug inside docutils (it's hard to see on their Sourceforge tracker), however, it would be good if `rstviewer` didn't crash, but was able to show the bug output in the rendered file, just like it does when subtitles are too short by just a single char.

Am happy to help out with any debugging if required 👍🏻

**Comment by terhorst** [comment]
Thanks for the report. Should be fixed in v0.0.7.

**Comment by terhorst** [comment]
Also, FWIW, in your example, docutils actually crashes, so there does not seem to be a useful error message I can print out beyond the traceback itself. If you increase the length of the underline a little bit, but not all the way, a useful error message eventually gets printed. Not sure what controls this behavior but I would agree that it's a bug in docutils.

**Comment by jamescooke** [comment]
@terhorst Thanks for the quick update 👍🏻 

I've reproduced the bug directly in docutils 0.16, then checked out the current master and it seems fixed.

**Comment by jamescooke** [comment]
Oh and the fix works great too! 🎉
